[tool.poetry]
name = "langgraph-agent"
version = "0.1.0"
description = ""
authors = ["oooo12-git <jhdmbwy12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.29.5"
python-dotenv = "^1.0.1"
langchain-teddynote = "^0.3.37"
langgraph = "^0.2.53"
langchain-openai = "^0.2.10"
yfinance = "^0.2.50"
pandas = "^2.2.3"
yahooquery = "^2.3.7"
deep-translator = "^1.11.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
